### ISSUE TITLE
Support for Node 22?

### ISSUE THREAD

**Issue by broksonic21** [strapi/pack-up#22]
### What version of `@strapi/blocks-react-renderer` are you using?

- Node 22.11.0
- Npm 10.9.0

### What's Wrong?

get a warning on npm install on the latest node lts

in both pack-up 4 and 5

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@strapi/pack-up@5.0.0',
npm warn EBADENGINE   required: { node: '>=18.0.0 <=20.x.x', npm: '>=6.0.0' },
npm warn EBADENGINE   current: { node: 'v22.11.0', npm: '10.9.0' }
npm warn EBADENGINE }
```

```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@strapi/pack-up@4.23.0',
npm warn EBADENGINE   required: { node: '>=18.0.0 <=20.x.x', npm: '>=6.0.0' },
npm warn EBADENGINE   current: { node: 'v22.11.0', npm: '10.9.0' }
npm warn EBADENGINE }
```

### To Reproduce

use node 22.11.0 and run npm install on either strapi 4 or 5

### Expected Behaviour

no warning for supported LTS's

**Comment by broksonic21** [comment]
Issue is here: https://github.com/strapi/pack-up/blob/main/package.json#L116

**Comment by sisirkon** [comment]
Seems like there is PR that was merged, with no tag generate, would like to know what the frequency for the next tag for release is.

https://github.com/strapi/pack-up/pull/23

**Comment by alex-strapi** [comment]
> Hi @alex-strapi , quick follow on the question above, would like to understand when the next release is so that I can plan accordingly, this would be helpful in updating node dependencies.

We're planning on another release next week. 
We release as a monorepo so check the main github pages releases for updates 👍

**Comment by derrickmehaffy** [comment]
Duplicate: https://github.com/strapi/pack-up/issues/24

**Comment by manuelbachl** [comment]
Any update on this? I get this warning with a fresh install:
```
npm warn EBADENGINE Unsupported engine {
npm warn EBADENGINE   package: '@strapi/pack-up@5.0.2',
npm warn EBADENGINE   required: { npm: '>=6.0.0', node: '>=18.0.0 <=20.x.x' },
npm warn EBADENGINE   current: { node: 'v22.12.0', npm: '11.0.0' }
npm warn EBADENGINE }
```
